### PR TITLE
Normalize and simply use of launcher and engine

### LINKED ISSUE #70: 🐛 | .chutney folder created when report forlder is different
## Describe the bug - What is the current behavior?

**.chutney** folder is created at the root of the project when running a scenario using the parameterized launcher.
```
Launcher("target/chutney/reports")
```

## Steps to reproduce

Run some test without using the default launcher constructor.

## What is the expected correct behavior?

This folder should not be created if not needed (in this case it is empty), as it can confuse user and clutter the project structure.

## Environment (please complete the following information):
 - Chutney version: chutney-kotlin-dsl 0.1.19
 - OS: Windows
 - Browser: n/a

### PR DESCRIPTION
**Pull request by nbrouand**
Fix #70 #66

### CODE REVIEW

File: dsl/src/main/kotlin/com/chutneytesting/kotlin/util/SystemEnvConfigurationParameters.kt [hunk 1]
```diff
@@ -0,0 +1,38 @@
+package com.chutneytesting.kotlin.util
```
Comment (boddissattva) [inline dsl/src/main/kotlin/com/chutneytesting/kotlin/util/SystemEnvConfigurationParameters.kt:1]: I think we have to avoid to have a dependency on junit apart from **junit.engine** package.

File: dsl/src/main/kotlin/com/chutneytesting/kotlin/launcher/Launcher.kt [hunk 2]
```diff
@@ -2,22 +2,50 @@ package com.chutneytesting.kotlin.launcher
...
 ) {
+    private val systemParameters = SystemEnvConfigurationParameters(null);
 
-    private val executionService = ExecutionService(environmentJsonRootPath)
+    init {
+        if(reportRootPathInput != null) {
+            System.setProperty(CONFIG_REPORT_ROOT_PATH.parameter,reportRootPathInput);
+        }
+    }
+    private val reportRootPath: String = systemParameters.get(CONFIG_REPORT_ROOT_PATH.parameter).orElse(CONFIG_REPORT_ROOT_PATH.defaultString())
```
Comment (boddissattva) [inline dsl/src/main/kotlin/com/chutneytesting/kotlin/launcher/Launcher.kt:33]: I think we should avoid to have the launcher depends on properties whose keys start with **junit.chutney**. The launcher has to be independent of junit.

File: dsl/src/main/kotlin/com/chutneytesting/kotlin/junit/engine/execution/ExecutionListeners.kt [hunk 3]
```diff
@@ -110,23 +111,9 @@ class FileWriterScenarioReportExecutionListener : EnabledTestExecutionListener(e
...
-        }
-    }
-
     override fun testPlanExecutionFinished(testPlan: TestPlan?) {
         if (enabled()) {
-            ofNullable(reportRootPathConfig).ifPresentOrElse(
-                { SiteGenerator(it).generateSite() },
-                { SiteGenerator().generateSite() }
-            )
+           SiteGenerator().generateSite()
```
Comment (boddissattva) [inline dsl/src/main/kotlin/com/chutneytesting/kotlin/junit/engine/execution/ExecutionListeners.kt:116]: We have here a regression because this generator doesn't take into account the JUnit properties file.

**Review by boddissattva — APPROVED** [review]
